file = open("challenge/input.txt", "w")
file.write("Python PLP")
file.write(" \n")
file.write("Weekly Challenge")
file.write(" \n")
file.write("Task Requirements")
file.write(" \n")
file.write("Python Scripts")
file.write(" \n")
file.write("File Handling")
